export const TOURNAMENT_DETAILS_RETRIEVED = 'TOURNAMENT_DETAILS_RETRIEVED';
export const NEW_TEAM_REGISTRATION_INITIATED = 'NEW_TEAM_REGISTRATION_INITIATED';
export const TEAM_INFO_ADDED = 'TEAM_INFO_ADDED';
export const NEW_TEAM_BOWLER_INFO_ADDED = 'NEW_TEAM_BOWLER_INFO_ADDED';
export const NEW_TEAM_PARTNERS_SELECTED = 'NEW_TEAM_PARTNERS_SELECTED';
export const NEW_TEAM_BOWLER_UPDATED = 'NEW_TEAM_BOWLER_UPDATED';