export const NEW_TOURNAMENT_INITIATED = 'NEW_TOURNAMENT_INITIATED';
export const NEW_TOURNAMENT_SAVED = 'NEW_TOURNAMENT_SAVED';
export const NEW_TOURNAMENT_STEP_COMPLETED = 'NEW_TOURNAMENT_STEP_COMPLETED';
export const NEW_TOURNAMENT_PREVIOUS_STEP_CHOSEN = 'NEW_TOURNAMENT_PREVIOUS_STEP_CHOSEN';
export const NEW_TOURNAMENT_COMPLETED = 'NEW_TOURNAMENT_COMPLETED';
