export const RESET = 'RESET';
export const TOURNAMENT_DETAILS_RETRIEVED = 'TOURNAMENT_DETAILS_RETRIEVED';
export const STRIPE_ACCOUNT_STATUS_CHANGED = 'STRIPE_ACCOUNT_STATUS_CHANGED';
export const TOURNAMENT_STATE_CHANGED = 'TOURNAMENT_STATE_CHANGED';
