import {Record} from "immutable";

export const TournamentRecord = Record({
  id: null,
  identifier: null,
  name: null,
  year: null,
  image_url: null,
  config_items: null,
  contacts: null,
  testing_environment: null,
  shifts: null,
  stripe_account: null,
  state: null,
  status: null,
  start_date: null,
  available_conditions: null,
  additional_questions: null,
  available_questions: null,
  bowler_count: null,
  team_count: null,
  free_entry_count: null,
  purchasable_items: null,
  chart_data: null,
});